# Generated by Django 4.2.4 on 2023-10-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_mail_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail_key',
            field=models.CharField(default='UQXfPlgw27iCjTbyJtad1pAvshku0B', max_length=30, verbose_name='ключ'),
        ),
    ]
